### ISSUE TITLE
module not working even for the sample email

### ISSUE THREAD

**Issue by Iron-Stark** [mynameisvinn/EmailParser#1]
Hi I was trying using your code in Python 3.6. and it gives the following error:

Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].sent_start

Not sure how to rectify this. Can you please help

**Comment by mynameisvinn** [comment]
spacy's apis have churned quite a bit. ive updated emailparser to reflect these changes - can you let me know if it didnt work?
